#!/usr/bin/env ruby
###
# Even Fibonacci numbers
# Problem 2
###
# Each new term in the Fibonacci sequence is generated by adding the previous
# two terms. By starting with 1 and 2, the first 10 terms will be:
#
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#
# By considering the terms in the Fibonacci sequence whose values do not exceed
# four million, find the sum of the even-valued terms.
#
# NOTES: Mathematically, the Fibonacci sequence is defined as 0, 1, 1, 2, 3, 5, ...
# I've implemented my find fibonacci methods accordingly.  This means however,
# that it must be taken into account that the Euler Problem is defined to begin
# at the second Fibonacci term, where fib(0)=0 and fib(1)=1.
#
###

TARGET = 4_000_000
SMALL_TARGET = 10

### Very concise recursive fibonacci method.  Consider revising to use this.
# Credit for this solution goes to Aja Hammerly's "A World Without Assignment"
# talk at the MountainWest RubyConf 2014.  On second consideration, implementation,
# and testing, it turns out that resursion takes much longer ~10sec than the
# iterative (looped) way which takes ~0.1sec.  Leaving all code here for further
# reference.  -sprestage 6/3/14
def fib(n)
  case n
  when 0
    0
  when 1
    1
  else fib(n-1) + fib(n-2)
  end
end

def find_xth_fibonacci_number(xth_term)
  if xth_term == 0
    return 0
  end
  if xth_term == 1
    return 1
  end
  if xth_term == 2
    return 1
  end
  fib_n_minus_two = 1
  fib_n_minus_one = 1
  fib_n = 0
  3.upto(xth_term) do |x|
    fib_n = fib_n_minus_two + fib_n_minus_one
    fib_n_minus_two = fib_n_minus_one
    fib_n_minus_one = fib_n
  end
  return fib_n
end

### First solution is the quickest.
def first_find_sum_of_even_fibonacci_terms_under(max)
  fib_sum = 0
  fib_n_minus_two = 1
  fib_n_minus_one = 1
  fib_n = 0

  until fib_n > max
    fib_n = fib_n_minus_one + fib_n_minus_two
    fib_n_minus_two = fib_n_minus_one
    fib_n_minus_one = fib_n
    if fib_n_minus_two % 2 == 0
      fib_sum += fib_n_minus_two
    end
  end

  return fib_sum
end

puts
print "1st solution, Sum of even Fibonacci terms under #{TARGET} = "
puts first_find_sum_of_even_fibonacci_terms_under(TARGET)

### Second solution is very slow.
def second_find_sum_of_even_fibonacci_terms_under(max)
  the_end = 0
  n = 1
  fib_sum = 0
  while the_end < max
    if the_end % 2 == 0
      fib_sum += the_end
    end
    n += 1
    the_end = fib(n)
  end
  return fib_sum
end

puts
print "2nd solution, Sum of even Fibonacci terms under #{TARGET} = "
puts second_find_sum_of_even_fibonacci_terms_under(TARGET)

### Third solution is also pretty quick.
def third_find_sum_of_even_fibonacci_terms_under(max)
  the_end = 0
  n = 1
  fib_sum = 0
  while the_end < max
    if the_end % 2 == 0
      fib_sum += the_end
    end
    n += 1
    the_end = find_xth_fibonacci_number(n)
  end
  return fib_sum
end

puts
print "3rd solution, Sum of even Fibonacci terms under #{TARGET} = "
puts third_find_sum_of_even_fibonacci_terms_under(TARGET)
puts

